### ISSUE TITLE
binary_sensor platform?

### ISSUE THREAD

**Issue by rct** [alphasixtyfive/home-assistant-configs#2]
I'm trying to use your binary_sensors like open_windows.yaml, but I'm having a problem putting it into my config because there is no platform defined.  I probably haven't had enough coffee yet, but all of the binary_sensors I've come across use value_template instead of state.  I seem to be missing something or being dumb.

Thanks for your help.

**Comment by alphasixtyfive** [comment]
This one should go under `template:`
