### ISSUE TITLE
Missing Home Assistant Config octopus_energy.yaml

### ISSUE THREAD

**Issue by davidgrob** [alphasixtyfive/home-assistant-configs#3]
Hi,
    I was following a link from home assistant community and it no longer exists.
https://github.com/alphasixtyfive/HomeAssistantConfigs/blob/main/octopus_energy.yaml

Is it possible to have a copy or re-instate the file?

Thanks

David

**Comment by alphasixtyfive** [comment]
There is one for Agile and one for Go tariff now:

https://github.com/alphasixtyfive/home-assistant-configs/blob/main/octopus_energy_agile.yaml

https://github.com/alphasixtyfive/home-assistant-configs/blob/main/octopus_energy_go.yaml
